export type {
  MascotAnchor,
  MascotBody,
  MascotColors,
  MascotFace,
  MascotMood,
  MascotShape,
  Oval,
  Pt,
  Slit,
} from "./geometry.js";
export {
  BODY_POINTS,
  FACE_BOX,
  MASCOT_MOODS,
  MASCOT_SHAPES,
  PACK_LENGTH,
  mascotAnchor,
  mascotBlush,
  mascotBody,
  mascotBodyPoints,
  mascotColors,
  mascotFace,
  mascotShine,
  mascotSlits,
  mascotSpark,
  mixHex,
  moodFromActivity,
  normalizeHex,
  packMascot,
  pointsToPath,
  seedFromName,
  slitColor,
  unpackMascot,
} from "./geometry.js";
export { MascotMark } from "./MascotMark.js";
export {
  GROGBOT_MARK_COLOR,
  type MascotMarkSvgOptions,
  mascotMarkElements,
  mascotMarkSvg,
} from "./svg.js";
