/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations/index'
import { Route as IntegrationsSlugRouteImport } from './routes/integrations/$slug'
import { Route as UseCasesIndexRouteImport } from './routes/use-cases/index'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases/$slug'
import { Route as IntegrationsCategoryCategoryRouteImport } from './routes/integrations/category/$category'
import { Route as LlmDottxtRouteImport } from './routes/llm[.]txt'
import { Route as LlmsDothhtmlRouteImport } from './routes/llms[.]html'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as AiDottxtRouteImport } from './routes/ai[.]txt'
import { Route as AiDotjsonRouteImport } from './routes/ai[.]json'
import { Route as IdentityDotjsonRouteImport } from './routes/identity[.]json'
import { Route as BrandDottxtRouteImport } from './routes/brand[.]txt'
import { Route as FaqAiDottxtRouteImport } from './routes/faq-ai[.]txt'
import { Route as DeveloperAiDottxtRouteImport } from './routes/developer-ai[.]txt'
import { Route as RobotsAiDottxtRouteImport } from './routes/robots-ai[.]txt'
import { Route as IndexDotmdRouteImport } from './routes/index[.]md'
import { Route as McpDotjsonRouteImport } from './routes/mcp[.]json'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as WellKnownMcpDotjsonRouteImport } from './routes/.well-known/mcp[.]json'
import { Route as WellKnownMcpServerCardDotjsonRouteImport } from './routes/.well-known/mcp/server-card[.]json'
import { Route as WellKnownApiCatalogRouteImport } from './routes/.well-known/api-catalog'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsSlugRoute = IntegrationsSlugRouteImport.update({
  id: '/integrations/$slug',
  path: '/integrations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIndexRoute = UseCasesIndexRouteImport.update({
  id: '/use-cases/',
  path: '/use-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/use-cases/$slug',
  path: '/use-cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsCategoryCategoryRoute =
  IntegrationsCategoryCategoryRouteImport.update({
    id: '/integrations/category/$category',
    path: '/integrations/category/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const LlmDottxtRoute = LlmDottxtRouteImport.update({
  id: '/llm.txt',
  path: '/llm.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDothhtmlRoute = LlmsDothhtmlRouteImport.update({
  id: '/llms.html',
  path: '/llms.html',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDottxtRoute = AiDottxtRouteImport.update({
  id: '/ai.txt',
  path: '/ai.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDotjsonRoute = AiDotjsonRouteImport.update({
  id: '/ai.json',
  path: '/ai.json',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityDotjsonRoute = IdentityDotjsonRouteImport.update({
  id: '/identity.json',
  path: '/identity.json',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandDottxtRoute = BrandDottxtRouteImport.update({
  id: '/brand.txt',
  path: '/brand.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqAiDottxtRoute = FaqAiDottxtRouteImport.update({
  id: '/faq-ai.txt',
  path: '/faq-ai.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperAiDottxtRoute = DeveloperAiDottxtRouteImport.update({
  id: '/developer-ai.txt',
  path: '/developer-ai.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsAiDottxtRoute = RobotsAiDottxtRouteImport.update({
  id: '/robots-ai.txt',
  path: '/robots-ai.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDotmdRoute = IndexDotmdRouteImport.update({
  id: '/index.md',
  path: '/index.md',
  getParentRoute: () => rootRouteImport,
} as any)
const McpDotjsonRoute = McpDotjsonRouteImport.update({
  id: '/mcp.json',
  path: '/mcp.json',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const WellKnownMcpDotjsonRoute = WellKnownMcpDotjsonRouteImport.update({
  id: '/.well-known/mcp.json',
  path: '/.well-known/mcp.json',
  getParentRoute: () => rootRouteImport,
} as any)
const WellKnownMcpServerCardDotjsonRoute = WellKnownMcpServerCardDotjsonRouteImport.update({
  id: '/.well-known/mcp/server-card.json',
  path: '/.well-known/mcp/server-card.json',
  getParentRoute: () => rootRouteImport,
} as any)
const WellKnownApiCatalogRoute = WellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/integrations/category/$category': typeof IntegrationsCategoryCategoryRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms.html': typeof LlmsDothhtmlRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/ai.txt': typeof AiDottxtRoute
  '/ai.json': typeof AiDotjsonRoute
  '/identity.json': typeof IdentityDotjsonRoute
  '/brand.txt': typeof BrandDottxtRoute
  '/faq-ai.txt': typeof FaqAiDottxtRoute
  '/developer-ai.txt': typeof DeveloperAiDottxtRoute
  '/robots-ai.txt': typeof RobotsAiDottxtRoute
  '/index.md': typeof IndexDotmdRoute
  '/mcp.json': typeof McpDotjsonRoute
  '/mcp': typeof McpRoute
  '/.well-known/mcp.json': typeof WellKnownMcpDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof WellKnownMcpServerCardDotjsonRoute
  '/.well-known/api-catalog': typeof WellKnownApiCatalogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/use-cases': typeof UseCasesIndexRoute
  '/integrations/category/$category': typeof IntegrationsCategoryCategoryRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms.html': typeof LlmsDothhtmlRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/ai.txt': typeof AiDottxtRoute
  '/ai.json': typeof AiDotjsonRoute
  '/identity.json': typeof IdentityDotjsonRoute
  '/brand.txt': typeof BrandDottxtRoute
  '/faq-ai.txt': typeof FaqAiDottxtRoute
  '/developer-ai.txt': typeof DeveloperAiDottxtRoute
  '/robots-ai.txt': typeof RobotsAiDottxtRoute
  '/index.md': typeof IndexDotmdRoute
  '/mcp.json': typeof McpDotjsonRoute
  '/mcp': typeof McpRoute
  '/.well-known/mcp.json': typeof WellKnownMcpDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof WellKnownMcpServerCardDotjsonRoute
  '/.well-known/api-catalog': typeof WellKnownApiCatalogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/integrations/category/$category': typeof IntegrationsCategoryCategoryRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms.html': typeof LlmsDothhtmlRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/ai.txt': typeof AiDottxtRoute
  '/ai.json': typeof AiDotjsonRoute
  '/identity.json': typeof IdentityDotjsonRoute
  '/brand.txt': typeof BrandDottxtRoute
  '/faq-ai.txt': typeof FaqAiDottxtRoute
  '/developer-ai.txt': typeof DeveloperAiDottxtRoute
  '/robots-ai.txt': typeof RobotsAiDottxtRoute
  '/index.md': typeof IndexDotmdRoute
  '/mcp.json': typeof McpDotjsonRoute
  '/mcp': typeof McpRoute
  '/.well-known/mcp.json': typeof WellKnownMcpDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof WellKnownMcpServerCardDotjsonRoute
  '/.well-known/api-catalog': typeof WellKnownApiCatalogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/integrations/$slug'
    | '/use-cases/$slug'
    | '/integrations/'
    | '/use-cases/'
    | '/integrations/category/$category'
    | '/llm.txt'
    | '/llms.html'
    | '/llms-full.txt'
    | '/ai.txt'
    | '/ai.json'
    | '/identity.json'
    | '/brand.txt'
    | '/faq-ai.txt'
    | '/developer-ai.txt'
    | '/robots-ai.txt'
    | '/index.md'
    | '/mcp.json'
    | '/mcp'
    | '/.well-known/mcp.json'
    | '/.well-known/mcp/server-card.json'
    | '/.well-known/api-catalog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/integrations/$slug'
    | '/use-cases/$slug'
    | '/integrations'
    | '/use-cases'
    | '/integrations/category/$category'
    | '/llm.txt'
    | '/llms.html'
    | '/llms-full.txt'
    | '/ai.txt'
    | '/ai.json'
    | '/identity.json'
    | '/brand.txt'
    | '/faq-ai.txt'
    | '/developer-ai.txt'
    | '/robots-ai.txt'
    | '/index.md'
    | '/mcp.json'
    | '/mcp'
    | '/.well-known/mcp.json'
    | '/.well-known/mcp/server-card.json'
    | '/.well-known/api-catalog'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/integrations/$slug'
    | '/use-cases/$slug'
    | '/integrations/'
    | '/use-cases/'
    | '/integrations/category/$category'
    | '/llm.txt'
    | '/llms.html'
    | '/llms-full.txt'
    | '/ai.txt'
    | '/ai.json'
    | '/identity.json'
    | '/brand.txt'
    | '/faq-ai.txt'
    | '/developer-ai.txt'
    | '/robots-ai.txt'
    | '/index.md'
    | '/mcp.json'
    | '/mcp'
    | '/.well-known/mcp.json'
    | '/.well-known/mcp/server-card.json'
    | '/.well-known/api-catalog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IntegrationsSlugRoute: typeof IntegrationsSlugRoute
  UseCasesSlugRoute: typeof UseCasesSlugRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  UseCasesIndexRoute: typeof UseCasesIndexRoute
  IntegrationsCategoryCategoryRoute: typeof IntegrationsCategoryCategoryRoute
  LlmDottxtRoute: typeof LlmDottxtRoute
  LlmsDothhtmlRoute: typeof LlmsDothhtmlRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  AiDottxtRoute: typeof AiDottxtRoute
  AiDotjsonRoute: typeof AiDotjsonRoute
  IdentityDotjsonRoute: typeof IdentityDotjsonRoute
  BrandDottxtRoute: typeof BrandDottxtRoute
  FaqAiDottxtRoute: typeof FaqAiDottxtRoute
  DeveloperAiDottxtRoute: typeof DeveloperAiDottxtRoute
  RobotsAiDottxtRoute: typeof RobotsAiDottxtRoute
  IndexDotmdRoute: typeof IndexDotmdRoute
  McpDotjsonRoute: typeof McpDotjsonRoute
  McpRoute: typeof McpRoute
  WellKnownMcpDotjsonRoute: typeof WellKnownMcpDotjsonRoute
  WellKnownMcpServerCardDotjsonRoute: typeof WellKnownMcpServerCardDotjsonRoute
  WellKnownApiCatalogRoute: typeof WellKnownApiCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$slug': {
      id: '/integrations/$slug'
      path: '/integrations/$slug'
      fullPath: '/integrations/$slug'
      preLoaderRoute: typeof IntegrationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/': {
      id: '/use-cases/'
      path: '/use-cases'
      fullPath: '/use-cases/'
      preLoaderRoute: typeof UseCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/use-cases/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/category/$category': {
      id: '/integrations/category/$category'
      path: '/integrations/category/$category'
      fullPath: '/integrations/category/$category'
      preLoaderRoute: typeof IntegrationsCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm.txt': {
      id: '/llm.txt'
      path: '/llm.txt'
      fullPath: '/llm.txt'
      preLoaderRoute: typeof LlmDottxtRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/llms.html': {
      id: '/llms.html'
      path: '/llms.html'
      fullPath: '/llms.html'
      preLoaderRoute: typeof LlmsDothhtmlRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/ai.txt': {
      id: '/ai.txt'
      path: '/ai.txt'
      fullPath: '/ai.txt'
      preLoaderRoute: typeof AiDottxtRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/ai.json': {
      id: '/ai.json'
      path: '/ai.json'
      fullPath: '/ai.json'
      preLoaderRoute: typeof AiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/identity.json': {
      id: '/identity.json'
      path: '/identity.json'
      fullPath: '/identity.json'
      preLoaderRoute: typeof IdentityDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/brand.txt': {
      id: '/brand.txt'
      path: '/brand.txt'
      fullPath: '/brand.txt'
      preLoaderRoute: typeof BrandDottxtRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/faq-ai.txt': {
      id: '/faq-ai.txt'
      path: '/faq-ai.txt'
      fullPath: '/faq-ai.txt'
      preLoaderRoute: typeof FaqAiDottxtRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/developer-ai.txt': {
      id: '/developer-ai.txt'
      path: '/developer-ai.txt'
      fullPath: '/developer-ai.txt'
      preLoaderRoute: typeof DeveloperAiDottxtRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/robots-ai.txt': {
      id: '/robots-ai.txt'
      path: '/robots-ai.txt'
      fullPath: '/robots-ai.txt'
      preLoaderRoute: typeof RobotsAiDottxtRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/index.md': {
      id: '/index.md'
      path: '/index.md'
      fullPath: '/index.md'
      preLoaderRoute: typeof IndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/mcp.json': {
      id: '/mcp.json'
      path: '/mcp.json'
      fullPath: '/mcp.json'
      preLoaderRoute: typeof McpDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/.well-known/mcp.json': {
      id: '/.well-known/mcp.json'
      path: '/.well-known/mcp.json'
      fullPath: '/.well-known/mcp.json'
      preLoaderRoute: typeof WellKnownMcpDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof WellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    },
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof WellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IntegrationsSlugRoute: IntegrationsSlugRoute,
  UseCasesSlugRoute: UseCasesSlugRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  UseCasesIndexRoute: UseCasesIndexRoute,
  IntegrationsCategoryCategoryRoute: IntegrationsCategoryCategoryRoute,
  LlmDottxtRoute: LlmDottxtRoute,
  LlmsDothhtmlRoute: LlmsDothhtmlRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  AiDottxtRoute: AiDottxtRoute,
  AiDotjsonRoute: AiDotjsonRoute,
  IdentityDotjsonRoute: IdentityDotjsonRoute,
  BrandDottxtRoute: BrandDottxtRoute,
  FaqAiDottxtRoute: FaqAiDottxtRoute,
  DeveloperAiDottxtRoute: DeveloperAiDottxtRoute,
  RobotsAiDottxtRoute: RobotsAiDottxtRoute,
  IndexDotmdRoute: IndexDotmdRoute,
  McpDotjsonRoute: McpDotjsonRoute,
  McpRoute: McpRoute,
  WellKnownMcpDotjsonRoute: WellKnownMcpDotjsonRoute,
  WellKnownMcpServerCardDotjsonRoute: WellKnownMcpServerCardDotjsonRoute,
  WellKnownApiCatalogRoute: WellKnownApiCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
